### ISSUE TITLE
[Question] Pre-release versions no longer appear on pypi.org

### ISSUE THREAD

**Issue by jeffreyhodge** [microsoft/playwright-python#1145]
Hello, I don't know where to ask this question.  Sorry if this is the wrong place.  I have recently noticed that I can no longer install playwright version 0.162.2 via pip.  Only 1.x versions appear to be available.  Were the prerelease versions recently removed from pypi.org?  The files are still in pythonhosted.org (https://files.pythonhosted.org/packages/packages/07/8c/7b450c96a8b06d4fa6086000e11f8d726c0ec3ce02c35b12e94422a927fa/playwright-0.162.2-py3-none-manylinux1_x86_64.whl).

Is there an index somewhere that still has the prelease versions?

**Comment by mxschmitt** [comment]
0.x released had to be removed because we ran into storage issues see [here](https://github.com/microsoft/playwright-python/issues/1144#issuecomment-1027821820). Since 0.x was back at the time considered experimental we removed them. Everything after 1.x stays on Pypi forever.

Sorry for the inconvenience, see [here](https://github.com/microsoft/playwright-python/releases/tag/v1.8.0a1) for a migration guide and we apologize again!
