### ISSUE TITLE
[Question]: page.goto(url, wait_until="networkidle") doesn't work

### ISSUE THREAD

**Issue by MirageTurtle** [microsoft/playwright-python#1262]
### Your question

# Overview
I want to use playwright to screenshot some site, and some of them are lazy-loading. So I guess wait_until="networkidle" may work. But it doesn't work well. Here is my test.

# Test and output
It may be the minimum code which can reproduce my problem I think. (I wait 10s because I want to see if the `networkidle` event work in this 10s.)
```python
import asyncio
from playwright.async_api import async_playwright


async def main(url):
    async with async_playwright() as p:
        browser = await p.firefox.launch()
        context = await browser.new_context()
        page = await context.new_page()
        page.on("domcontentloaded", lambda: print("page domcontentloaded!"))
        page.on("load", lambda: print("page loaded!"))
        page.on("networkidle", lambda: print("page networkidle!"))
        resp = await page.goto(
            url,
            wait_until="networkidle"
        )
        print("start wait")
        await page.wait_for_timeout(10000)
        print("stop wait")
        screenshot = await page.screenshot(path="page_screenshot.png")


if __name__ == "__main__":
    url = "https://mirageturtle.github.io"
    asyncio.run(main(url))
```

Here is the output:
```zsh
page domcontentloaded!
page loaded!
page domcontentloaded!
page loaded!
start wait
stop wait
```

It will be appreciated if you have any idea about this issue or any suggestion for screenshot lazy-loading webpage(except hard wait).

**Comment by MirageTurtle** [comment]
Python version: python 3.9.10
playwright version: 1.20.0

**Comment by mxschmitt** [comment]
> `page.on("networkidle", lambda: print("page networkidle!"))`

This is not an event which Playwright emits. Only domcontentloaded and load is a valid one: https://playwright.dev/docs/api/class-page#page-event-dom-content-loaded

**Comment by mxschmitt** [comment]
networkidle is not the best indicator if a website is "ready to be screenshoted". Actually there is no way to guarantee that a website finished loading except the load and domcontentloaded event, since it can fetch data asynchronously or fetch every 100ms some network resources. This would result that networkidle would never resolve / the state would never be reached. (Keep in mind that every website is different and you probably don't control them)

You don't have to check if networkidle has occurred, if you pass it to page.goto, it will internally make sure that the state has occurred.

**Comment by MirageTurtle** [comment]
Thank you very much for helping!

You're right, every website is different and you probably don't control them. I screenshot many sites, and some sites are in loading. Maybe I just can guarantee I can screenshot all perfectly by wait. ahaa.

I'll close this issue soon, and feel free to reopen it if you need.
