### ISSUE TITLE
[BUG] Playwright hangs when ran in a thread

### ISSUE THREAD

**Issue by gtzampanakis** [microsoft/playwright-python#1327]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Fedora
- Node.js version: 16.1.0
- Browser: All

The following program causes playwright to hang while trying to exit the context manager:

```
import asyncio
from playwright.async_api import async_playwright
import threading

async def do_playwright_stuff():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto("http://playwright.dev")
        print(await page.title())
        await browser.close()
        print('Closed browser')

def asyncio_loop():
    asyncio.run(do_playwright_stuff())

def main():
    th = threading.Thread(target = asyncio_loop)
    th.start()
    th.join()

main()
```

**Comment by mxschmitt** [comment]
I tried to run the code locally and its working for me with Python 3.8. I see that you are using Fedora, which is not an official supported Linux distribution of Playwright, see [here](https://playwright.dev/docs/library#system-requirements). This might be the reason why it's not working as expected.

**Comment by gtzampanakis** [comment]
I know that Fedora is unsupported however I don't have Ubuntu installed to test it there.

Python is 3.8.

**Comment by mxschmitt** [comment]
I was testing it on Ubuntu 20 with Python 3.8 as well. Since it's not officially supported I unfortunately have to close it. If you have a fix for it and it's reasonable, feel free to open a pull request so others benefit from it as well.

**Comment by jalbano** [comment]
Not sure it's related, but I'm seeing what might be similar. I have code that works fine if I don't "stop" the playwright instance and hangs if I do. So, I'd be curious if it "works" for you if you change the "with ..." line to just...

p = await async_playwright().start()

I have "works" in quotes because this isn't really working, right? The reason I'm back looking at this line of my own code is that I'm now getting "Too many files open" errors and assume it has something to do with not stopping the playwright instance after each call.
