### ISSUE TITLE
Google Cloud App Engine support?

### ISSUE THREAD

**Issue by mattduffield** [microsoft/playwright-python#1338]
### Your question

Hello, I am curious if Google Cloud App Engine is supported? I am using Playwright 1.22 using a standard app.yaml file for app engine. When I try and invoke Playwright, it gives me the message, "Looks like Playwright was just installed..." I have tried to execute `playwright install` in the terminal but it says that the OS is not supported and it is falling back to Ubuntu. I still get an error whenever I try to invoke my Playwright functions.

Please advise as how to configure App Engine? If not, should I use Cloud Run or something else?

Thanks in advanced!

**Comment by DiMiTriFrog** [comment]
Or for AWS Lambda? I cant get it yet..

**Comment by mxschmitt** [comment]
Google Cloud App Engine is not officially supported. Launching browsers requires a bunch if installed operating system dependencies, which is most likely the reason why it does not work there.

(if you can use Docker there, it most likely just works)

Since this is not in scope for the Playwright project (compatibility with Google Cloud App Engine) I'm closing it for now. If you find any helpful insides with your research, we would definitely an update here or maybe even a contribution in the docs for future users.
