### ISSUE TITLE
[Question]: RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by baiyyee** [microsoft/playwright-python#1339]
### Your question

When trying to do UI automtion with pytest-asyncio and pytest-playwright, I got exception like: **RuntimeError: Cannot run the event loop while another loop is running**

**Code structure:**
```
ui2/conftest.py
ui2/test_bing.py
```

**ui2/conftest.py**

```
import pytest
import asyncio


@pytest.fixture(scope="session")
def event_loop():
    """重写event_loop"""

    loop = asyncio.get_event_loop()
    yield loop
    loop.close()
```

**ui2/test_bing.py**

```
import pytest

from playwright.async_api import Page


@pytest.mark.asyncio
async def test_bing(page: Page):
    await page.goto("http://www.bing.com")
```

**env:**
```
pytest==7.1.2
pytest-asyncio==0.18.3
pytest-playwright==0.3.0
```

**Detail exception as below:**

![image](https://user-images.githubusercontent.com/4414171/170166462-f3ffd79f-fdde-47ee-a73a-c8b0585642a1.png)

**Comment by mxschmitt** [comment]
`pytest-playwright` only exposes sync bindings, thats why it's not compatible with the async version of Playwright.

See this feature request to also provide async bindings: https://github.com/microsoft/playwright-pytest/issues/74

**Comment by nathanielobrown** [comment]
I'm finding this an issue for a slightly different reason. Some of my tests are `async` but most are not, and none of the tests that use Playwright are `async`. Unfortunately, the tests that use Playwright cause an event loop to be opened for the remainder of the session as a result of the `browser` fixture with session scope. This then conflicts with my `async` tests trying to open a new event loop, causing the exception `RuntimeError: Cannot run the event loop while another loop is running`. I need asyncio for some of my other tests, so this is an issue.

I guess I can override the `browser` fixture so that it is `module` scope or even more granular, but do you have any other ideas or advice?

**Comment by feluelle** [comment]
You can use `nest-asyncio` to patch asyncio to use nested event loops:

```python
import nest_asyncio
nest_asyncio.apply(browser._loop)
```

should do the job.
