### ISSUE TITLE
[BUG] playwright._impl._api_types.Error: Executable doesn't exist

### ISSUE THREAD

**Issue by Mateusz404** [microsoft/playwright-python#1359]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows
- Python version: 3.10
- Browser: Firefox
- Extra: -

**Describe the bug**

_playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Mateusz\AppData\Local\ms-playwright\firefox-1323\firefox\firefox.exe
\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557
\u2551 Looks like Playwright was just installed or updated.       \u2551
\u2551 Please run the following command to download new browsers: \u2551
\u2551                                                            \u2551
\u2551     playwright install                                     \u2551
\u2551                                                            \u2551
\u2551 <3 Playwright Team                                         \u2551
\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d_

firefox folder (firefox.exe is missing):
![image](https://user-images.githubusercontent.com/61477470/173591758-3693cdfe-db9a-4cc6-bef7-43c237313f6e.png)

proof of proper installation:
![image](https://user-images.githubusercontent.com/61477470/173591691-1dd78346-a640-4116-a88b-e2a8d4acce4b.png)

playwright install doesn't do anything?
![image](https://user-images.githubusercontent.com/61477470/173591901-9cb11178-9db5-4a5c-b5c5-f4802d8079d5.png)

**Comment by mxschmitt** [comment]
There is no firefox.exe which is kinda odd. Could you try removing the `C:\Users\Mateusz\AppData\Local\ms-playwright\firefox-1323\` and run `playwright install` again?

**Comment by Mateusz404** [comment]
That's the output:
![image](https://user-images.githubusercontent.com/61477470/173592881-aae785b3-a76f-460c-9a02-a44805a7999e.png)

**Comment by mxschmitt** [comment]
Do you have a special anti virus software installed? Seems like Playwright extracts it, and then the firefox.exe gets removed again -> permission denied error appears because of that.

**Comment by mxschmitt** [comment]
just out of curiosity, which virus software are you using? we could try to investigate then why it was flagged.

**Comment by Mateusz404** [comment]
> just out of curiosity, which virus software are you using? we could try to investigate then why it was flagged.

https://www.avast.com/pl-pl/free-antivirus-download

**Comment by vl-tech** [comment]
In my case the issue was that playwright path was not correct when running playwrighti nstall from the project directory using pycharm. i had to manually go to this directory : C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts and run playwright.exe install from there so the pycharm can find the browser , otherwise it gave error executable does not exist .I do not know why pycharm is unable to find the playwright exe by default ... its not an antivirus issue in my case 

`C:\Users\Owner\PycharmProjects\UdemyPythonMegaCourse> playwright install
playwright : The term 'playwright' is not recognized as the name of a cmdlet, function, script  
file, or operable program. Check the spelling of the name, or if a path was included, verify    
that the path is correct and try again.
At line:1 char:1
+ playwright install
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (playwright:String) [], CommandNotFoundException  
    + FullyQualifiedErrorId : CommandNotFoundException
`
`C:\Users\Owner\PycharmProjects\UdemyPythonMegaCourse> cd C:\Users\Owner\AppData\Local\Package
s\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts`
`.\playwright.exe install` RUN AT THE SAME DIR
