### ISSUE TITLE
[BUG] Headless mode not working inside Docker

### ISSUE THREAD

**Issue by brian-edgar-re** [microsoft/playwright-python#1507]
**Context:**
- Playwright Version: 0.3.0 (the one that installs when following the tutorial: https://playwright.dev/python/docs/intro, https://pypi.org/project/pytest-playwright/)
- Operating System: Mac (on host Machine).
- Python version: 3.7.6 (on host Machine).
- Browser: Chromium
- Extra: I'm running everything inside docker.

**Code Snippet**

I uploaded an example of the issue I'm having: https://github.com/brian-edgar-re/playwright-python-docker-example

In the readme it contains the steps to reproduce the issue:
docker build -t example_playwright_python -f Dockerfile .
docker-compose up

**Describe the bug**

The main problem is that, when running playwright python inside docker, [it raises an error](https://github.com/brian-edgar-re/playwright-python-docker-example#steps-for-reproducing-the-issue) which says that I'm running in headed mode, when actually [the documentation says that by default it runs in headless mode](https://playwright.dev/python/docs/ci#running-headed). Also tried passing the headless: True parameter but it also rised the same error.

**Comment by mxschmitt** [comment]
you need to do: `xvfb-run pytest` then it's possible to launch a headed browser without a GUI.

Unrelated to that, I saw you are using the Node.js Docker image, we have a dedicated one for Python: https://playwright.dev/python/docs/docker

**Comment by brian-edgar-re** [comment]
Hi @mxschmitt , thanks for your fast reply. I followed your suggestion and I wasn't able to run the tests. In fact, it got stuck, even 40 minutes later I didn't have any progress on the tests. When running docker-compose up, the only output I had was:

`
Recreating playwright-python-docker-example_playwright_python_1 ... done
Attaching to playwright-python-docker-example_playwright_python_1
`

The changes you can find them in this branch: https://github.com/brian-edgar-re/playwright-python-docker-example/tree/fix/running-headless-mode

Do you know what is happening that I'm not able to run the tests?

**Comment by mxschmitt** [comment]
So I was trying it out and had a few findings:

- if you want to use xvfb-run inside Docker, you need to say [`init: true` or `docker run ... --init`](https://stackoverflow.com/a/59813158/6512681)
- You had the `PWDEBUG` env set, which always ends up in running tests in headed mode
- Usually there is not a lot of value to run tests headed, since it requires more CPU/memory - but that's your choice
- You were creating your context manually, pytest-playwright actually does it [for you](https://playwright.dev/python/docs/test-runners#run-with-a-custom-browser-channel-like-google-chrome-or-microsoft-edge). 

See here for my diff: https://github.com/brian-edgar-re/playwright-python-docker-example/compare/fix/running-headless-mode...mxschmitt:make-it-work?expand=1

**Comment by brian-edgar-re** [comment]
Thanks for your fast response @mxschmitt . With the changes you suggested, it finally works! The main point of this issue was running in headless mode as I mentioned in the title (I never wanted to run playwright in headed mode, but it is also helpful to have this other alternative in case I need to use it in the future). Now I can start playing with playwright and use it as a replacement for cypress. Thank you very much for all your help! :)
