### ISSUE TITLE
I want to reduce the size of docker, how can I do it

### ISSUE THREAD

**Issue by jw-star** [microsoft/playwright-python#1594]
### Your question

I have modified these places，where do i need to modify

https://github.com/jw-star/playwright-python/blob/bc7090c6e4598d07604d4b4bfb2218ccc0e51e7b/utils/docker/Dockerfile.jammy#L43

https://github.com/jw-star/playwright-python/blob/bc7090c6e4598d07604d4b4bfb2218ccc0e51e7b/.github/workflows/publish_release_docker.yml#L18

**Comment by mxschmitt** [comment]
Dockerfile wise these changes are enough, publishing wise more stuff needs to be changed, since we re publish to Microsoft Container Registry and not to Docker hub.

We'd recommend sticking to the official docker images or building your own image based on a custom dockerfile, since our dockerfile requires a local build of Playwright for python.

Doing `playwright install chromium --with-deps` should be enough after you installed Playwright via PIP.

**Comment by jw-star** [comment]
ok thanks, I'll build the mirror entirely myself
