### ISSUE TITLE
docs: Page Object Model example

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-python#164]
We should add an example how to apply the POM pattern which is common with Selenium and e2e testing in general with Playwright Python.

Source: https://playwright.slack.com/archives/CSUHZPVLM/p1596901222104000?thread_ts=1596754031.088200&cid=CSUHZPVLM

**Comment by naro** [comment]
Hi,

is there the updated documentation about POM on playwright-python? I have read the Slack thread and tried to search the recent commits but I can't find anything yet. 

Many thanks,
Radim

**Comment by mxschmitt** [comment]
Hi, its pretty much the same as the JavaScript variant: https://playwright.dev/#version=v1.4.2&path=docs%2Fpom.md&q=

**Comment by naro** [comment]
Sorry for my ignorance, I did not get it after an hour of different attempts. I'm an old school Python developer so I tried subclassing but that does not seem to be the correct way. A custom class with `page` in __init__ also is not the correct way because it does not know the other Page methods.
I've got an error `TypeError: a coroutine was expected, got None` (or a Response) so the POM should be a coroutine? It's something I still did not get my head around :( 

Would you mind posting a minimal example, please?

**Comment by mxschmitt** [comment]
Yeah let me try it out and add it to the documentation. Are you using the sync or async variant?

**Comment by naro** [comment]
Thank you. I'm using the sync variant. 
I managed to get it to work now with a custom `__getattr__`. I'm not sure if that's the correct way but it works at least.

The minimal variant with the custom goto method would be 
```
class CustomPage:

    def __init__(self, page: Page):
        self.page = page

    def goto(self):
        return self.page.goto('https://bing.com')

    def __getattr__(self, attr):
        return getattr(self.page, attr)

page =  CustomPage(browser.newPage())
```
