### ISSUE TITLE
[Question]: When start a page as head mode and it tooks too long to open the page as it costed 10s.

### ISSUE THREAD

**Issue by AllenLuosong** [microsoft/playwright-python#1674]
### Your question

as you can see , my script is as blelow, and I run it in the pytest. but it costs too long to open the url, as while the web browser is white page. My question, why it takes so long.
page.goto(url=url)
![image](https://user-images.githubusercontent.com/57619311/204729489-99c0371b-b76d-45dd-a652-c27b0cb76bad.png)

here is some infomation that you can refer to
platform win32 -- Python 3.9.6, pytest-7.2.0, pluggy-1.0.0
plugins: allure-pytest-2.11.1, Faker-15.3.3, base-url-2.0.0, ordering-0.6, playwright-0.3.0

**Comment by AllenLuosong** [comment]
here is a video for open the page and you can see how it slow.
[be3dd13708c7b690b90ec6e879e3bf6b.webm](https://user-images.githubusercontent.com/57619311/205421184-7ee34286-199f-48b0-b829-b92249a8408e.webm)

and here is my code 
**test.py**
`import re
from playwright.sync_api import Page, expect


def test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page(page: Page):
    page.goto("https://playwright.dev/")

    # Expect a title "to contain" a substring.
    expect(page).to_have_title(re.compile("Playwright"))

    # create a locator
    get_started = page.get_by_role("link", name="Get started")

    # Expect an attribute "to be strictly equal" to the value.
    expect(get_started).to_have_attribute("href", "/docs/intro")

    # Click the get started link.
    get_started.click()

    # Expects the URL to contain intro.
    expect(page).to_have_url(re.compile(".*intro"))

def test_homepage_zhihu(page: Page):
    page.goto("https://www.zhihu.com/")

    # Expect a title "to contain" a substring.
    expect(page).to_have_title(re.compile("zhihu"))`

**pytest.ini**
`[pytest]
addopts= -vsx  --screenshot="on" --video="on" -p no:warnings
#  --headed  `

**Comment by mxschmitt** [comment]
I guess its slow because your machine has either not enough CPU or memory available. Also the hardware could be not powerful enough.

You could try identifying which exact API call is slow, try to disable screenshot and video recording to see how it performs without that. Set `DEBUG=pw:protocol` env var which will print protocol logs, so we can identify if e.g. the navigation is slow, or a single resource takes long time to load. From our side we cant act on it yet, since you are the first person complaining about performance issues, so most likely its caused by your setup/hardware.

**Comment by mxschmitt** [comment]
Closing since its stale, please open a new issue with a clear repro and logs. See above for more information.
