### ISSUE TITLE
how to set timeout of the whole task?

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#1721]
### Your question

if i have 100 accounts,  each task is to open 100 urls and fill 100 forms.
each task set to 10  minutes,  it the task took too long after 10 minutes,  then close the browser and begin next account

How to set the 10 minutes limits?
thank .

**Comment by mxschmitt** [comment]
Since this is a more generic Python question, I recommend reaching out to StackOverflow or to our [Discord](https://aka.ms/playwright/discord) server.

Generally speaking, make sure to not overload your system by giving each browser context 2 logic CPU cores. The rest should be possible to implement using asyncio worker pools.
