### ISSUE TITLE
[Question]: locators not only one, how to do if i wanna the second locator?

### ISSUE THREAD

**Issue by garyzhang21** [microsoft/playwright-python#1756]
### Your question

just like selenium find_elements. 
how to do if i use click?

**Comment by garyzhang21** [comment]
selector : str
            A selector to search for an element. If there are multiple elements satisfying the selector, the first will be
            used.

in other words, if i want to use the second one, what should i do?

**Comment by mxschmitt** [comment]
You are using page.click right? You should never do this exactly because of that, because when using the page.click, page.fill methods, they are not strict and always use the first element.

What you should do instead is to use [Locators](https://playwright.dev/docs/locators#strictness), they are [strict](https://playwright.dev/docs/locators#strictness) and you can easily configure that you want e.g. the second element via [nth(2)](https://playwright.dev/docs/locators#get-by-nth-item). Via Locators you can also click, fill, etc.

**Comment by garyzhang21** [comment]
i see. thank you 
 eg: page.locator(xpath),
and it does not support this  when parameter is xpath, right ?

**Comment by mxschmitt** [comment]
It does, nth works with all the Playwright selectors

**Comment by garyzhang21** [comment]
> It does, nth works with all the Playwright selectors

i see. thank you so much.
