### ISSUE TITLE
[Feature] expect.soft() for Python

### ISSUE THREAD

**Issue by mentalfabric** [microsoft/playwright-python#1925]
Sure would be nice if we could get soft assertions on the Python side. We're currently trying implementing Playwright for our test automation at my workplace and any time an `expect` fails it ends the entire test. This means that we have to revert back to using the Pytest `with check asserts` whenever we just need a soft assertion.

Please implement expect.soft() on the Python side of Playwright. It already exists for the Javascript side.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-python/issues/1272

**Comment by muzammilzahoor291-cloud** [comment]
Anyone waiting for the [11th class result 2026](https://11classresultonline.pk/) can benefit from this straightforward guide. The instructions are easy to follow and provide useful information about checking first-year examination results. Instead of searching through multiple sources, students can understand the basic process here and then verify their result through the relevant official board.
