### ISSUE TITLE
[REGRESSION]:  page.goto can not redirect  url

### ISSUE THREAD

**Issue by allenluosong** [microsoft/playwright-python#2064]
**Context:**
- BAD Playwright Version: 1.37
- Operating System:Windows

**Code Snippet**

```python
import re
from playwright.sync_api import Page, expect


def test_dx_page(page: Page):
    page.goto("https://dx.10086.cn/9zbMFg")
    page.wait_for_timeout(5000)
```

**Describe the bug**

the url for https://dx.10086.cn/9zbMFg is a short H5 link when enter it in browser it will redirect to https://[gd.10086.cn/gmccapp/webpage/netAssistant/index.html](https://gd.10086.cn/gmccapp/webpage/netAssistant/index.html#/index)#/index. But when I used playwright to open it,  I got a http status of 404 for https://dx.10086.cn/9zbMFg, it did not redirect .

**Comment by mxschmitt** [comment]
Looks like the website has some kind of bot protection system in place, most likely in https://gd.10086.cn/gmccapp/hLj5UhsEkAwr/JbwfgPHP8mLG.6771a74.js. 

Since Playwright focuses on end-to-end testing, which expects that you as a tester owns the site which you are testing, we can't recommend anything else than disabling the bot protection / WAF system.

Closing as per above, since we can't act on that.

**Comment by allenluosong** [comment]
I found what keep me out of this site, the file you found is a debugger file, and it stoped me to continue my test case. However I do not how to do with this situation.
