### ISSUE TITLE
[BUG] The input elements does not fill correctly

### ISSUE THREAD

**Issue by khalidnecron** [microsoft/playwright-python#2087]
### System info
- Playwright Version: v1.38.0
- Operating System: Windows 11
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("https://shorturl.at/fwARZ")
    page.get_by_label("Contraseña").type("password")
    page.get_by_label("Confirmar Contraseña").type("password")
    page.screenshot(path="test.png")
    browser.close()
```

**Steps**
- [Run the code]

**Expected**

Both input elements get fill

**Actual**

Only one input element gets fill

**Comment by yury-s** [comment]
`page.get_by_label("Contraseña")` resolves to the same element as `page.get_by_label("Confirmar Contraseña")` because by default playwright matches a case-insensitive substring. In theory, changing the string to `page.get_by_label("Contraseña:*", exact=True).type("password")` should work but it looks like first label is not associate with the first input, so as a workaround you can replace it with `page.locator('#new-password').type("password")`:

```py
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://shorturl.at/fwARZ")
    # page.get_by_label("Contraseña:*", exact=True).type("password")
    page.locator('#new-password').type("password")
    page.get_by_label("Confirmar Contraseña").type("password")
    page.screenshot(path="test.png")
    browser.close()
```

Will that work?

**Comment by yury-s** [comment]
`page.get_by_label("Contraseña:*", exact=True).type("password")` does not work because there is a bug in the label, it should be `<label for="new-password"` rather than `<label for="Password"`:

![image](https://github.com/microsoft/playwright-python/assets/9798949/e7f75d54-0a64-41dc-9200-708d9b26fb4c)
