### ISSUE TITLE
Install browsers upon pip install, not the first launch

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#21]
That improves user experience

**Comment by mxschmitt** [comment]
Made some research. There is no good native way of having a postinstall script. It could be implemented like that with egg_info which is super hacky, not sure how it performs: https://stackoverflow.com/a/45021666/6512681

**Comment by pavelfeldman** [comment]
O actually made it work as described here: https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools

But pip is suppressing the I/O, so there are no progress bars visible, which defeats the purpose of this UX improvement.

**Comment by mxschmitt** [comment]
I thought about the following design when we compare it with other tools like .

- They have a command line interface which they use to download files. In their case language models `spacy download en_core_web_sm`
- It can be exposed via `setup.py` like package.json>bin in the Node.js world
- If no browsers are persistent, I would download the used browser on launch() instead of all browsers

So the user can decide, either use the CLI to download the browser or the used browser get's downloaded on launch.

**Comment by pavelfeldman** [comment]
That's probably it, we'll have the `plagwright install` for now

**Comment by ColdHeat** [comment]
Thanks for working playwright, it's much needed for automated tests. 

I personally think that I would rather have browsers installed during the `pip install` step even if it didn't have progress bars. 

I looked around for a way to automatically install browsers on first test run perhaps and it looks like you would have to modify `sys.argv` to use the existing `main()` install.

https://github.com/microsoft/playwright-python/blob/fc5485c6057da52d80e5aa9ddcba1fb71e15b2ab/playwright/main.py#L123-L133

Could the install function perhaps be extracted this into a separate function that can be called without modifying `sys.argv`?
