### ISSUE TITLE
[Question] Is there any reason not to use greenlets to achieve concurrency with a single browser instance in the sync API?

### ISSUE THREAD

**Issue by michaeleveringham** [microsoft/playwright-python#2101]
### Your question

There are many issues (such as https://github.com/microsoft/playwright-python/issues/1207 and https://github.com/microsoft/playwright-python/issues/623) that discuss Playwright sync API not being thread safe, not to mention the `greenlet.error: cannot switch to a different thread` error message that attempting to shunt requests into a thread will yield.

However, is there any reason to avoid using `greenlet`s to dispatch concurrent requests from a single instance via the sync API? My goal here was to dispatch requests up to a max limit at a time (akin to `ThreadPoolExecutor` and it's initialisation kwarg `max_workers`).

Ideally, one would just use the async API, but if you're stuck in a legacy codebase and that is not an option, is this okay? Example below.

## System info

- Mac M1
- Python 3.9.11
- `playwright==1.27.1`
- `gevent==22.10.1`

## Example code

```python
from collections import deque

from gevent.pool import Pool
from playwright.sync_api import Page, sync_playwright


def get(page: Page, url: str):
    print(f"Navigating to {url}...")
    return page.request.get(url)


def send_concurrent_requests(page: Page, max_greenlets: int, urls: list[str):
    greenlets = []
    url_queue = deque(urls)
    pool = Pool(max_greenlets)

    while url_queue:
        pool.wait_available()
        url = url_queue.popleft()
        greenlets.append(pool.spawn(get, page, url))
    pool.join()
    responses = [g.value for g in greenlets]
    return responses


playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=True)
context = browser.new_context()
page = context.new_page()
max_greenlets = 2
urls = [
    "https://bing.com/",
    "https://google.com/",
    "https://yahoo.com/",
    "https://stackoverflow.com/",
    "https://github.com/",
]
responses = send_concurrent_requests(page, max_greenlets, urls)
print(responses)
```

## Conclusion

My above implementation _seems_ to work well, but I was a bit surprised by it as I couldn't find examples of anyone else using this pattern online... which made me think perhaps there is a reason it isn't used. Some clarification from Playwright devs or even seasoned `greenlet`/`gevent` capable developers would be appreciated!

**Comment by mxschmitt** [comment]
While your pattern isn't directly interacting with the browser, as it uses `page.request.get` which acts as an HTTP client, interacting with the browser in parallel through multiple threads isn't natively supported. Think of it like this: in the real world, a browser is typically controlled by one person at a time.

Under the hood, Playwright for Python/Java/.NET communicates with the Playwright driver through the stdio of a subprocess. Concurrency issues may arise when multiple threads attempt to write to the subprocess simultaneously, leading to race conditions or unexpected behaviors.

Concurrency, especially with browser automation, is tricky. Playwright primarily serves end-to-end testing scenarios where concurrency within a single browser isn't typical. If you truly require parallelism, consider using the async version inside a thread, where you can create multiple tasks and wait for results or spawn a sync Playwright per thread. If you're solution above works for your use-case, then I'd also keep it, since it seems to parallelise inside the same thread using greenlets and you don't do cross-thread references/calls.

**Comment by michaeleveringham** [comment]
Thank you for the detailed response. I think for the very limited purpose I have here (making multiple `APIRequestContext.get` calls concurrently within an existing sync API Playwright environment), it works well and with likely limited potential for issue given each request is isolated from another. I think trying to do something like `page.goto` would be a bad idea like this though; it may work, but likely with unexpected output, especially at scale. Perhaps spawning a new `Page` for each greenlet would be okay though? Alas, I have no need for this so though so don't plan to test that behaviour right now.

Thanks again! Going to close this.
