### ISSUE TITLE
How to change the default timeout setting for playwright python?

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2187]
How to change the default timeout setting for playwright python? I know this can be done when using Typescript but how can it be done in python?

**Comment by mxschmitt** [comment]
In what issue did you run? Not always is increasing timeouts the best solution in order to fix a test. Playwright is based on multiple timeouts (here are the most important ones):

- https://playwright.dev/python/docs/api/class-browsercontext#browser-context-set-default-timeout
- https://playwright.dev/python/docs/api/class-browsercontext#browser-context-set-default-navigation-timeout
- https://playwright.dev/python/docs/test-assertions#setting-a-custom-timeout

And you can specify a timeout to each action and assertion in order to override the default timeout.
