### ISSUE TITLE
[BUG] playwright 1.40.0 is strictly depend on pyee==11.0.1

### ISSUE THREAD

**Issue by vzhirnov** [microsoft/playwright-python#2190]
### System info

- Playwright Version: 1.40.0
- Operating System: macos monterey  12.2.1
(Apple M1)

- Other info:

pyee==11.0.1

**Steps**
Try to update pyee from version 11.0.1 to 11.1.0

**Expected**

update pyee from version 11.0.1 to 11.1.0 is completed successfully.

**Actual**

We cannot install new pyee version, because
```
The conflict is caused by:
    The user requested pyee==11.1.0
    playwright 1.40.0 depends on pyee==11.0.1
```

Is that the correct behaviour? Do we need use pyee with only 11.0.1 version and not above?

**Comment by vzhirnov** [comment]
The issue is updated. I'm sorry, I initially specified the wrong version of the operating system.

**Comment by RazerM** [comment]
This is a general issue I'm facing too where greenlet is also pinned. This seems needlessly restrictive.

The commits that bump pyee and greenlet have no code changes, so there doesn't seem to be a compatibility reason (and even then, ranges like `'greenlet>=3.0.0,<4,!=3.0.1'` would be better)

**Comment by christopher-watanabe-snkeos** [comment]
On a related note, I recently noticed failing tests due to [AsyncIOEventEmitter deprecation in pyee v12.0.0](https://github.com/jfhbrook/pyee/releases/tag/v12.0.0). I was using a the much older v1.13.1 playwright and was not pinning the dependencies.

I updated and pinned the versions as follows: 
playwright == 1.47.0
pyee == 12.0.0
greenlet == 3.0.3

And my tests ran as expected.

**Comment by mborsetti** [comment]
Any chance you can stop pinning so we don't have to live in dependency (and installation) hell?

Also see #2564 for more pinning woes
