### ISSUE TITLE
How to wait a new page loading？

### ISSUE THREAD

**Issue by AdelaPro2** [microsoft/playwright-python#2331]
When I click, the page will jump to a new page (referring to when logging in, clicking the login button will enter the product's homepage)

How should I determine if a new page (which is always a different URL) has been loaded successfully?

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord) 

---

General advise for waiting for new pages see here:

- https://playwright.dev/python/docs/pages#handling-popups
- https://playwright.dev/python/docs/api/class-pageassertions#page-assertions-to-have-url
