### ISSUE TITLE
How to Dynamically pass values inside this locator

### ISSUE THREAD

**Issue by yeswanth-ds** [microsoft/playwright-python#2393]
### Please do not submit this issue.

- [X] I understand

**Comment by yeswanth-ds** [comment]
This is the locator captured using Playwright Inspector-
locator("tbody").filter(has_text=re.compile(r"^AU Health Insurance$")).get_by_role("cell") 
I need to pass values inside this locator how to do that ? the one which I tried is not working
page.locator("tr").filter(has_text=re.compile(r"^datadictvalue["C_PLAN_TYPE"]")).get_by_role("cell")

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

--

This might help you:

https://stackoverflow.com/a/55810892/6512681
