### ISSUE TITLE
What is the value list for local in Playwright？

### ISSUE THREAD

**Issue by AdelaPro2** [microsoft/playwright-python#2436]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
