### ISSUE TITLE
When I open the browser using playwright.chromium. launch_persistent_context, I use page. go to open a URL for example https://111.html To manually open a URL for the tag page https://222.html The tag page does not have a URL when calling context. pages https://222.html What is the reason for the page, and how can I obtain the second page?

### ISSUE THREAD

**Issue by Liu-boyu** [microsoft/playwright-python#2445]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

---

You are probably interested in context.pages: https://playwright.dev/python/docs/api/class-browsercontext#browser-context-pages
