### ISSUE TITLE
chrome://flags or IPV6/IPV4 control

### ISSUE THREAD

**Issue by gryffus** [microsoft/playwright-python#2533]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by gryffus** [comment]
Requesting reopen, the issue description was not updated on issue creation. Fixed now.

**Comment by gryffus** [comment]
Created a new one https://github.com/microsoft/playwright-python/issues/2534
