### ISSUE TITLE
Issues in docs

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#454]
Please feel free to post your findings about the docs here. We often have some JS leftovers in the Python docs...

**Comment by mrudulp** [comment]
List of things I noticed for v1.8a1 _(more will be appended as I find them)_
1. Providing a link to documentation page under supported languages would be a good improvement. instead of finding it from github
2. https://playwright.dev/python/docs/ci seems to talk about how to do things npm/JS way and not python way.
3. most of the links on https://hub.docker.com/_/microsoft-playwright page end up to not found page
4. Is there a docker image already for Python playwright? Documentation gives an impression there is one
5. if you search for waitFor it throws few links in the page I clicked one Element selectors | Playwright where it was present. haven't checked others I am assuming those in search might be there on page or the indexes for search need updating
