### ISSUE TITLE
[Feature Request] Support tracing in playwright-python

### ISSUE THREAD

**Issue by fili** [microsoft/playwright-python#575]
Already supported by other version of playwright, see:
https://playwright.dev/docs/api/class-chromiumbrowser#chromiumbrowserstarttracingpage-options

I understand it is browser specific but it can be very useful for web performance auditing and testing, to be able to extract the trace.json file (with screenshots). 

Can we extend the already Chromium specific features with tracing?
https://playwright.dev/python/docs/api/class-chromiumbrowsercontext

**Comment by pavelfeldman** [comment]
@fili do you have experience working with tracing? What are your expectations there? The reason I ask is that tracing is very rarely the answer. Could you share more about the information you'd like to collect?

**Comment by fili** [comment]
@pavelfeldman yes, one example is that I want the trace.json so I can extract the filmstrip. If you have a better method for that I love to try that.

**Comment by pavelfeldman** [comment]
I see, so that is your debugging story. We don't have tracing exposed in Python yet, let me keep this open and schedule it for the next release.

We are working on a similar cross-browser story for Playwright, but it isn't ready yet. For now you can record video or manually use https://playwright.dev/python/docs/api/class-cdpsession to capture the trace, but it might be the easiest to wait for it to be added into the API.

**Comment by mxschmitt** [comment]
added in #611
