### ISSUE TITLE
ENV workaround for "python -m playwright install""

### ISSUE THREAD

**Issue by fili** [microsoft/playwright-python#576]
Working with Python venv (3.8) on Ubuntu 20.04 LTS I encountered the following error:

```
"chromium" browser was not found.
 Please complete Playwright installation via running
"python -m playwright install"
```

Of course I tried the following command but that did not do anything (browsers using in playwright were already installed outside the env).

Solved it with a workaround by running:
```
PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install
```
This then redownloaded and installed the browsers within the env.

Afterwards adding this line to the top of my main python script (which evokes playwright) to make sure my code could find the browsers within the env:

```
os.environ['PLAYWRIGHT_BROWSERS_PATH'] = '0'
```

I am perfectly fine with this solution as I find it cleaner to install the browsers within the virtual env instead of the user dir. I also utilize this solution in my docker images based on Debian 10.

Leaving this here as @mxschmitt indicated this is not expected behavior and for others running into this similar issue and provide the workaround :)

**Comment by Mattwmaster58** [comment]
I'm encountering this "<browser> was not found" error as well. I've even debugged the library and it's using the correct path for the browser which definitely does exist, but for some reason this error still occurs.

**Comment by pavelfeldman** [comment]
I think this is working as expected. Your environment is probably specifying the `XDG_CACHE_HOME` environment variable that Playwright uses instead of the home folder when installing the browsers. You can work around it via pointing `PLAYWRIGHT_BROWSERS_PATH` to a particular folder once and for all. You don't need to download browsers twice, just make sure you want them in this particular fixed location.
