### ISSUE TITLE
Explore sync API possibilities

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#61]

**Comment by mxschmitt** [comment]
Pro:
- debugging experience is only good with sync code since the common REPLs rely on pdb/ipdb/ipython and they don't support async/await
- No REPL afaik available which does that
- less code for the user since methods are sync and some async
- Most Python is sync, so its not confusing for the user
Con:
- different from the Javascript API
- (performance disadvantages, but not sure)
- probably a weird Implementation in Playwright Python.

**Comment by pavelfeldman** [comment]
> different from the Javascript API

I don't think it is a big deal - we'll just tell Python users to not write await everywhere. It would anyways be different (`gather` vs `Promise.all`, `asyncio.ensure_future` all over the place.

> (performance disadvantages, but not sure)

Not sure where those would come from - execution will be exactly the same

> probably a weird Implementation in Playwright Python.

Nobody would need to know - we could actually re-do the entire API instead of a proxy wrapper to preserve all the typing information.

**Comment by bednaJedna** [comment]
hi there, for me, as a tester, sync API would be a definitely a selling point. Because I would not use this library alone, but with some testing framework, like behave or pytest. And for example, behave framework supports asyncio but comparing to non-async code, it is a mess, imho. In the case of async, I would use some JavaScript library/framework straight away.

**Comment by mxschmitt** [comment]
> hi there, for me, as a tester, sync API would be a definitely a selling point. Because I would not use this library alone, but with some testing framework, like behave or pytest. And for example, behave framework supports asyncio but comparing to non-async code, it is a mess, imho. In the case of async, I would use some JavaScript library/framework straight away.

Yep we are working on it want to have the sync version by default. Should be ready in 1-2 weeks!

**Comment by mxschmitt** [comment]
Closed since a first version was shipped which seems to work by testing it on an internal project.
