### ISSUE TITLE
Runtime warning for mobile example in readme

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright-python#65]
Running the [mobile and geo example](https://github.com/microsoft/playwright-python#mobile-and-geolocation) from readme gives the following runtime warning. Python 3.8.3 on macOS 10.15

```
mobile.py:18: RuntimeWarning: coroutine 'Page.waitForEvent' was never awaited
  await page.waitForRequest('*preview/pwa')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by mxschmitt** [comment]
Good catch @arjun27! Seems like Google has changed something on their website (waitForRequest does not resolve anymore since the request does not come in anymore). Also the example in the normal Playwright repository does not work anymore: https://playwright.dev/#version=v1.2.1&path=README.md&q=mobile-and-geolocation

Maybe switch to something more independent like [that](https://try.playwright.tech/?s=alwik) but not sure.

**Comment by mxschmitt** [comment]
@arjun27 this seems quite a nice alternative: https://mylocation.org/

**Comment by pavelfeldman** [comment]
We are now using sync examples
