### ISSUE TITLE
[FEATURE] Support distribution for PPC64LE 

### ISSUE THREAD

**Issue by serjb9** [microsoft/playwright-python#758]
**Context:**

- Playwright Version: 1.21.1
- Operating System: Unix/PPC64LE
- Python Version: 3.8

**Code Snippet**

```bash
:~ # arch
ppc64le
:~ # pip3 install playwright==1.12.1
Collecting playwright==1.12.1
  Could not find a version that satisfies the requirement playwright==1.12.1 (from versions: )
No matching distribution found for playwright==1.12.1
```

**Describe the bug**

Hi, I wonder if there any chance or plans to support playwright distribution for PPC64LE platforms?
Thanks.

**Comment by mxschmitt** [comment]
There is probably no support it in the near and long future, because not a lot of people have asked for it and we would need to setup a whole testing and build (for compiling browsers) infrastructure for it.

The only way currently of using it with ppc64le would be to use the Node.js variant with the Chromium browser which you install via your system package-manager. This should work today.

**Comment by mxschmitt** [comment]
Closed since we don't add ppc64le support in the near future.
