### ISSUE TITLE
[Bug]: load extension in broswer not in content

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#962]
### Playwright version

lasted

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

what i want is:
1, use a browser to load metamask extension for all contents for all pages
2, each content use a different proxy
3  after every  task,   i have to close the content but keep the broswer , the extension for next content.
so , i think   launch_persistent_context  doesnt fit me.

in this way, the browser is in private mode, how to  open in normal way?
maybe that 's why i can not find the extension.

thank you for your help.

### Code snippet to reproduce your bug

```shell
def work1():
    args = [
            f'--disable-extensions-except={chrome_extension}',
            f'--load-extension={chrome_extension}',
            ]

    playwright  = sync_playwright().start()
    browser = playwright.chromium.launch( headless=False, args=args)
    context = browser.new_context(  )
    page = context.new_page()

if __name__ == '__main__':
    work1()
```

**Comment by mxschmitt** [comment]
You'd have to launch Chromium for every session since launchPersistentContext gives you a browser context.

Using launchPersistentContext will give you a normal window (!= incognito).

Closing since its already answered in https://github.com/microsoft/playwright-python/issues/957#issuecomment-945624829.
